usuario:
  url: http://localhost:8080

spring:
  application:
    name: AgendadorTarefas

  data:
    mongodb:
      uri: mongodb://localhost:27017/user-api

  datasource:
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

    com:
      yanvelasco:
        agendadortarefas: DEBUG